my_profile:
  outputs:
    dev_trino:
      type: trino
      catalog: iceberg
      schema: staging
      host: localhost
      port: 8081
      user: admin
      password: ""
      http_scheme: http
    dev_postgres:
      type: postgres
      host: localhost
      user: airflow
      password: airflow
      port: 5432
      dbname: airflow
      schema: football
  target: dev_trino
