
---
version: '1'
 
services:
  metabase:
    image: metabase/metabase:v0.50.17
    container_name: metabase
    hostname: metabase
    volumes:
     - ./metabase/starburst-5.0.0.metabase-driver.jar:/plugins/starburst-5.0.0.metabase-driver.jar
     - ./volumes/metabase-data:/metabase
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase/h2.db
      MB_PLUGINS_DIR: /plugins
    networks:
      - shared_network

networks:
  shared_network:
    external: true