
---
version: '1'
 
services:
  minio:
    hostname: minio
    image: minio/minio:RELEASE.2024-07-16T23-46-41Z.fips
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './volumes/minio/data/:/data'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_DEFAULT_BUCKETS: datalake
    command: server --console-address ":9001" /data
    
  # This job will create the "datalake" bucket on Minio
  mc-job:
    image: minio/mc:RELEASE.2024-07-15T17-46-06Z.fips
    entrypoint: |
      /bin/bash -c "
      sleep 5;
      /usr/bin/mc config --quiet host add myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb --quiet myminio/datalake
      "
    depends_on:
      - minio