
---
version: '1'
 
services:
  postgres-dw:
    image: postgres:13-alpine
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: dw_root
      POSTGRES_PASSWORD: BraSil5WorldCups
      POSTGRES_DB: football
    volumes:
      - ./volumes/postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dw_root"]
      interval: 5s
      retries: 5
    restart: always
    networks:
      - shared_network
  
  minio:
    hostname: minio
    image: minio/minio:RELEASE.2024-07-16T23-46-41Z.fips
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './volumes/minio/data/:/data'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_DEFAULT_BUCKETS: datalake
    command: server --console-address ":9001" /data
    networks:
      - shared_network
    
  # This job will create the "datalake" bucket on Minio
  mc-job:
    image: minio/mc:RELEASE.2024-07-15T17-46-06Z.fips
    entrypoint: |
      /bin/bash -c "
      sleep 5;
      /usr/bin/mc config --quiet host add myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb --quiet myminio/datalake
      "
    depends_on:
      - minio
    networks:
      - shared_network
  
  hive-metastore:
    hostname: hive-metastore
    image: 'starburstdata/hive:3.1.2-e.18'
    ports:
      - '9083:9083' # Metastore Thrift
    environment:
      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://postgres:5433/football
      HIVE_METASTORE_USER: dw_root
      HIVE_METASTORE_PASSWORD: BraSil5WorldCups
      HIVE_METASTORE_WAREHOUSE_DIR: s3://datalake/
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_PATH_STYLE_ACCESS: "true"
      REGION: ""
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_ABFS_OAUTH: ""
      AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
      AZURE_ABFS_OAUTH_CLIENT_ID: ""
      AZURE_ABFS_OAUTH_SECRET: ""
      AZURE_ABFS_OAUTH_ENDPOINT: ""
      AZURE_WASB_ACCESS_KEY: ""
      HIVE_METASTORE_USERS_IN_ADMIN_ROLE: "admin"
    depends_on:
      - postgres-dw
    networks:
      - shared_network
  
  coordinator:
    image: "trinodb/trino:422" 
    ports:
      - "8081:8081"
    container_name: "coordinator"
    volumes:  
      - ./trino/etc:/etc/trino
    networks:
      - shared_network

  metabase:
    image: metabase/metabase:v0.50.17
    container_name: metabase
    hostname: metabase
    volumes:
     - ./metabase/starburst-5.0.0.metabase-driver.jar:/plugins/starburst-5.0.0.metabase-driver.jar
     - ./volumes/metabase-data:/metabase
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase/h2.db
      MB_PLUGINS_DIR: /plugins
    networks:
      - shared_network

networks:
  shared_network:
    external: true