brazil_football:
  outputs:
    dev:
      dbname: football
      host: airflow-postgres-1
      pass: airflow
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: airflow
  target: dev
